// <auto-generated />
namespace OOP2016MusicLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class NoImg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoImg));
        
        string IMigrationMetadata.Id
        {
            get { return "201606011901545_NoImg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
